name: Update pnpm lockfile
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Find the project folder by package.json "name"
      - name: Locate project directory
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          # Search for package.json files and pick the one whose "name" matches your app
          MAPFILE=()
          while IFS= read -r -d '' f; do MAPFILE+=("$f"); done < <(git ls-files -- '**/package.json' -z)

          TARGET=""
          for f in "${MAPFILE[@]}"; do
            if jq -e '.name=="black-jeopardy-app"' "$f" >/dev/null 2>&1; then
              TARGET="$(dirname "$f")"
              break
            fi
          done

          if [ -z "$TARGE]()
