name: Update pnpm lockfile
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (with Corepack)
        uses: actions/setup-node@v4
        with:
          node-version: '20'        # >= 18.17 is fine; 20 is good
          cache: 'pnpm'

      # EITHER Corepack (recommended if package.json has "packageManager": "pnpm@9.x")
      - name: Activate pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm -v

      # OR use the official pnpm action (uncomment these 4 lines and delete the Corepack step above)
      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: 9
      #     run_install: false

      - name: Install (regenerate lockfile)
        run: pnpm install --no-frozen-lockfile

      - name: Commit lockfile if changed
        run: |
          if ! git diff --quiet pnpm-lock.yaml; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add pnpm-lock.yaml
            git commit -m "ci: sync pnpm-lock.yaml with package.json"
            git push
          else
            echo "No lockfile changes"
          fi
